# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.6.8"
  # Uncomment this and any needed lines below if your project has dependencies needed for install
  # apt_packages:
  #   - mpich
  jobs:
    post_create_environment:
      # Install poetry
      - pip install docs/requirements.txt
    post_install:
      # Generate the API documentation
      - cd docs ; make html
sphinx:
  configuration: docs/conf.py