# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  # Uncomment this and any needed lines below if your project has dependencies needed for install
  # apt_packages:
  #   - mpich
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group.
      #   Installing everything is overkill, but I keep running 
      #   into this problem if I don't: https://github.com/python-poetry/poetry/issues/4493
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras --with docs
      # Generate the API documentation
      - cd docs ; make html
sphinx:
  configuration: docs/conf.py
