# Theme
ZSH_THEME="refined"
export PATH=$PATH_TO_COPY

# Plugins
plugins=(git zsh_reload)

if [[ -r ~/.oon.docker.zsh ]]; then
   source ~/.oon.docker.zsh
else
    source "$ZSH/oh-my-zsh.sh"
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

