# Theme
ZSH_THEME="refined"
export PATH=$PATH_TO_COPY

# Plugins
plugins=(git)

source "$ZSH/oh-my-zsh.sh"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi
