# Theme
ZSH_THEME="refined"

# Make sure to append here, because Conda has added itself
# to the PATH at this point, and we want to keep that
export PATH=${PATH_TO_COPY}:${PATH}

# Plugins
plugins=(git)

source "$ZSH/oh-my-zsh.sh"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Remove any duplicates from the 
typeset -U PATH
